---
title: "Synthetic Data"
author: "Hsuan Lee"
output: pdf_document
---
```{r}
setwd(paste("C:/Users/HsuanLee/Desktop/Methodology and Statistics/",
"Changepoints Inference in Relational Event Data of a Social Network/",
"ResearchArchive/Simulation_study_1", sep = ""))
```

# Simulate the REH
```{r}
# Install the needed packages

install.packages("devtools")

library(devtools)

devtools::install_version("mvtnorm", version = "1.1-3", repos = "http://cran.us.r-project.org")

devtools::install_github("TilburgNetworkGroup/remify@1a165e99a0ad784ead08974da86fb2a319f537dc")

devtools::install_github("TilburgNetworkGroup/remstats@c6ef7c41c6b43891f760d2db7ad390e8035b83dc")

devtools::install_github("TilburgNetworkGroup/remstimate@5ba940645929c4d9d84a4cf16fab68f8971a1a19")
```

```{r}
devtools::install_github("mlmeijerink/REHdynamics")
```

```{r}
library(tidyverse)
library(REHdynamics) # generate the REH with CPs
library(remstats) # the formula for REH
library(remify)
library(relevent) # fit REH to REM
```

```{r}
set.seed(9252568)
# REH with only inertia statistics
# ??remstat -> to select the statistics
formula <- ~ 1 + remstats::send("z", covar) + # Exogenous statistics
  remstats::difference("z", covar) + # Exogenous statistics
  remstats::inertia(scaling = "std") + # Endogenous statistics
  remstats::outdegreeSender(scaling='std') # Endogenous statistics

# set up the covariates
covar <- data.frame(id = 1:30, time = 0, z = rnorm(n = 30))
```

# REH with no CPs
```{r}
# set up the value of parameters
param.ncp <- list(
  "baseline" = -8.8,
  "z_send"= 0.1, 
  "z_difference" = -0.1,
  "inertia" = 0.18, # change it to 0.1
  "outdegreeSender" = 0.12) # change it to 0.1

# create REH with 1 CP
reh_ncp <- list()

rep <- 15 # replication times (number of datasets you wanna get)

# try parallel here
for (i in 1: rep){
  reh_ncp[[i]] <- generate(formula = formula, param = param.ncp, M = 10000, covar = covar)
  print(i)
}
```

**Save the Data**
```{r}
# Save the created REH
saveRDS(object = reh_ncp, file = "../Data/Synthetic_Data/REH_NCP.RDS")
```

# REH with 1 CP for inertia, none for the rest
```{r}
set.seed(9252568)
# REH with only inertia statistics
#formula <- ~ 1 + remstats::inertia(scaling = "std")

# set up the covariates
#covar <- data.frame(id = 1:30, time = 0, z = rnorm(n = 30))

# set up the value of parameters
param.1cp <- list(
  "baseline" = -8.8,
  "z_send"= 0.12, 
  "z_difference" = -0.1,
  
  "inertia" = function(t) {
    # set the location of CP
    if(t < 38200) { # window 56, 57, 58
      0.15
    } else  {
      0.06}
  },
  
  "outdegreeSender" = 0.12
)

# create REH with 1 CP
reh_1cp <- list()

rep <- 15 # replication times (number of datasets you wanna get)

for (i in 1: rep){
  reh_1cp[[i]] <- generate(formula = formula, param = param.1cp, M = 10000, covar = covar)
  print(i)
}
```

**Save the Data**
```{r}
# Save the created REH
saveRDS(object = reh_1cp, file = "../Data/Synthetic_Data/REH_1CP.RDS")
```

# REH with 1 CP for all the statistics (at same location)
```{r}
set.seed(9252568)
# REH with only inertia statistics
#formula <- ~ 1 + remstats::inertia(scaling = "std")

# set up the covariates
#covar <- data.frame(id = 1:15, time = 0, z = rnorm(n = 15))

# set up the value of parameters
param.1cp_same.all <- list(
  "baseline" = -8.8,
  
  "z_send"= function(t) {
    # set the location of CP
    if(t < 38200) { # window 56, 57, 58
      0.18
    } else  {
      0.04}
  },
  
  "z_difference" = function(t) {
    # set the location of CP
    if(t < 38200) { # window 56, 57, 58
      -0.05
    } else  {
      -0.15}
  },
  
  "inertia" = function(t) {
    # set the location of CP
    if(t < 38200) { # window 56, 57, 58
      0.13
    } else  {
      0.06}
  },
  
  "outdegreeSender" = function(t) {
    # set the location of CP
    if(t < 38200) { # window 56, 57, 58
      0.13
    } else  {
      0.07}
  }
)

# create REH with 1 CP
reh_1cp_same.all <- list()

rep <- 15 # replication times (number of datasets you wanna get)

for (i in 1: rep){
  reh_1cp_same.all[[i]] <- generate(formula = formula, param = param.1cp_same.all, M = 10000, covar = covar)
  print(i)
}
```

**Save the Data**
```{r}
# Save the created REH
saveRDS(object = reh_1cp_same.all, file = "../Data/Synthetic_Data/REH_1CP_same.all.RDS")
```

# REH with 2 CPs for inertia, none for the rest
```{r}
set.seed(9252568)
# REH with only inertia statistics
#formula <- ~ 1 + remstats::inertia(scaling = "std")

# set up the covariates
#covar <- data.frame(id = 1:15, time = 0, z = rnorm(n = 15))

# set up the value of parameters
param.2cp <- list(
  "baseline" = -8.8,
  "z_send"= 0.12, 
  "z_difference" = -0.11,
  
  "inertia" = function(t) {
    # set the location of CP
    if(t < 16750) { # window 24, 25, 26
      0.01
      } else
        
        if(t < 53900) { # window 79, 80, 81
          0.12
          } else {-0.01}
  },
  
  "outdegreeSender" = 0.12
)

# create REH with 1 CP
reh_2cp <- list()

rep <- 15 # replication times (number of datasets you wanna get)

for (i in 1: rep){
  reh_2cp[[i]] <- generate(formula = formula, param = param.2cp, M = 10000, covar = covar)
  print(i)
}
```

**Save the Data**
```{r}
# Save the created REH
saveRDS(object = reh_2cp, file = "../Data/Synthetic_Data/REH_2CP.RDS")
```

# REH with 2 CPs for all the statistics (at same location)
```{r}
set.seed(9252568)
# REH with only inertia statistics
#formula <- ~ 1 + remstats::inertia(scaling = "std")

# set up the covariates
#covar <- data.frame(id = 1:15, time = 0, z = rnorm(n = 15))

# set up the value of parameters
param.2cp_same.all <- list(
  "baseline" = -8.8,
  
  "z_send"= function(t) {
    # set the location of CP
    if(t < 16750) { # window 24, 25, 26
      0.2
    } else
      
      if(t < 53900) { # window 79, 80, 81
          -0.01
          } else {0.19}
    },
  
  "z_difference" = function(t) {
    # set the location of CP
    if(t < 16750) { # window 24, 25, 26
      -0.01
    } else
      
      if(t < 53900) { # window 79, 80, 81
          -0.12
          } else {0.03}
    },
  
  "inertia" = function(t) {
    # set the location of CP
    if(t < 16750) { # window 24, 25, 26
      0.02
      } else
        
        if(t < 53900) { # window 79, 80, 81
          0.14
          } else {0.03}
    },
  
  "outdegreeSender" = function(t) {
    # set the location of CP
    if(t < 16750) { # window 24, 25, 26
      -0.01
      } else
        
        if(t < 53900) { # window 79, 80, 81
          0.14
          } else {0.01}
    }
)

# create REH with 1 CP
reh_2cp_same.all <- list()

rep <- 15 # replication times (number of datasets you wanna get)

for (i in 1: rep){
  reh_2cp_same.all[[i]] <- generate(formula = formula, param = param.2cp_same.all, M = 10000, covar = covar)
  print(i)
}
```

**Save the Data**
```{r}
# Save the created REH
saveRDS(object = reh_2cp_same.all, file = "../Data/Synthetic_Data/REH_2CP_same.all.RDS")
```
